# Generated by Django 6.0.4 on 2026-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('policy', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Domain Policies',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('final_score', models.FloatField()),
                ('verdict', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('PHISHING', 'Phishing')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
